// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCnqb8UF4u_wYMAhxUJOPcE6ZkMXqrjS8',
    appId: '1:540545096280:web:cacd46f941a6eb3668082d',
    messagingSenderId: '540545096280',
    projectId: 'examen-final-equipo1',
    authDomain: 'examen-final-equipo1.firebaseapp.com',
    storageBucket: 'examen-final-equipo1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AK67HA4_7e75067e0p8PUdnbSbCwDqs',
    appId: '1:540545096280:android:07da1d6fd8dfd11068082d',
    messagingSenderId: '540545096280',
    projectId: 'examen-final-equipo1',
    storageBucket: 'examen-final-equipo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJEXfpZ6v7nEaC5TpLtFNsTyyBr5UxNA',
    appId: '1:540545096280:ios:91623eae57928be668082d',
    messagingSenderId: '540545096280',
    projectId: 'examen-final-equipo1',
    storageBucket: 'examen-final-equipo1.appspot.com',
    iosBundleId: 'com.example.examenFinalEquipo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAJEXfpZ6v7nEaC5TpLtFNsTyyBr5UxNA',
    appId: '1:540545096280:ios:09d6f4908e5569bd68082d',
    messagingSenderId: '540545096280',
    projectId: 'examen-final-equipo1',
    storageBucket: 'examen-final-equipo1.appspot.com',
    iosBundleId: 'com.example.examenFinalEquipo1.RunnerTests',
  );
}
